export const GET_CUSTOMER_PENDING = 'GET_CUSTOMER_PENDING';
export const GET_CUSTOMER_FULLFILLED = 'GET_CUSTOMER_FULLFILLED';
export const GET_CUSTOMER_REJECTED = 'GET_CUSTOMER_REJECTED';

export const GET_ROOM_PENDING = 'GET_ROOM_PENDING';
export const GET_ROOM_FULLFILLED = 'GET_ROOM_FULLFILLED';
export const GET_ROOM_REJECTED = 'GET_ROOM_REJECTED';
